version: 0.2

phases:
  install:
    commands:
      - npm install -g aws-cdk
      - npm install
  build:
    commands:
      - echo "Synthesizing CDK stack for student 9020861..."
      - cdk synth

artifacts:
  files:
    - 'cdk.out/CdkAssignment22020861Stack.template.json'
